### ISSUE TITLE
Can't use on MacOS 15

### ISSUE THREAD

**Issue by lziiid** [fkguo/zotero-inspire#33]
After I install the plugin and right click the paper item, there is no item "Update INSPIRE Metadata".
I use Zotero 7.0.7.
The debug panel raise the following errors:

［JavaScript Error："Error running bootstrap method'startup'on zoteroinspire@itp.ac.cn"］
［JavaScript Error："this.globalCache is undefined" ｛file："jar:file:///Users/lziiid/Library/Application%20Support/Zotero/Profiles/4t9iOwak.default
/extensions/zoteroinspire@itp.ac.cn.xpi!/chrome/content/scripts/zoteroinspire.js" line: 1287｝］
［JavaScript Error： "uncaught exception: undefined"］
［JavaScript Error： "uncaught exception: undefined"］

**Comment by fkguo** [comment]
I never had such a problem, so I don't know how to reproduce it. I use MacOS 15, and zotero 7.0.8-beta.... (before that I was using 7.0.6-beta...). Would an update of your zotero solve the problem?

**Comment by LB-4** [comment]
I get the same behavior and error messages on 7.0.11 running on MacOS 15.2:

Error running bootstrap method 'startup' on zoteroinspire@itp.ac.cn
this.globalCache is undefined zoteroinspire.js:1287
