### ISSUE TITLE
[Feature request] add citation counts source

### ISSUE THREAD

**Issue by jlu511** [fkguo/zotero-inspire#4]
Would it be possible to add a citation counts source, ie. [easyScholar](https://easyscholar.cc/) or [Crossref](https://www.crossref.org/), or [Semantic Scholar](https://www.semanticscholar.org/), or [Google Scholar](https://scholar.google.com/)? Like the plugin "Green Frog" https://github.com/redleafnew/zotero-updateifsE.

**Comment by fkguo** [comment]
Citations from INSPIRE with and without self-citations can be found in the extra field. Is this what you want?

**Comment by jlu511** [comment]
> > Some journals in other fields are not included in INSPIRE, such as Advanced Materials
> 
> Citation counts from CrossRef added when the paper is not in INSPIRE.

thank you ,but the released plugin does not support Zotero 7.

**Comment by fkguo** [comment]
> thank you ,but the released plugin does not support Zotero 7.

You're welcome. You may use prerelease v0.3.2 for Zotero 7, which was just published.
