### ISSUE TITLE
右键菜单不显示“更新inspire元数据”

### ISSUE THREAD

**Issue by hych0317** [fkguo/zotero-inspire#41]
作者你好，我安装插件后，选定条目并右键找不到插件对应的按钮，请问是需要进行什么操作吗？

![image](https://github.com/user-attachments/assets/a7157cd6-af23-478b-abee-f286bc5af648)

**Comment by fkguo** [comment]
重启 zotero 试一下

**Comment by hych0317** [comment]
> 重启 zotero 试一下

我已经尝试了，会不会是插件之间冲突了

**Comment by hych0317** [comment]
确实是插件冲突，我排查一下
