### ISSUE TITLE
Conflicted with "zotero attanger" add-on

### ISSUE THREAD

**Issue by phd-csy** [fkguo/zotero-inspire#50]
Bravo add-on for physics students! However, if "zotero attanger" and "zotero-inspire" are both enabled, the "zotero-inspire" doesn't work unless the former is disabled.

**Comment by phd-csy** [comment]
My environment is Zotero7.0.9 in Win11

**Comment by fkguo** [comment]
I have both enabled and had no problem so far... maybe because of some other plugins?

**Comment by fkguo** [comment]
I installed Jasminum just now, enabled both Jasminum and Zotero Attanger, but could not reproduce the problem. Sorry that I cannot help. I'm using 7.0.10-beta.3+56ae6d979 and did not have problems for previous versions either.

**Comment by phd-csy** [comment]
> I installed Jasminum just now, enabled both Jasminum and Zotero Attanger, but could not reproduce the problem. Sorry that I cannot help. I'm using 7.0.10-beta.3+56ae6d979 and did not have problems for previous versions either.

It has been solved by install "zotero-inspire" firstly and then the others. Thanks for your work!
