### ISSUE TITLE
Tag with "no transit" on ALL records

### ISSUE THREAD

**Issue by dpasserone** [fkguo/zotero-inspire#54]
![image](https://github.com/user-attachments/assets/68e53039-7622-4f0e-8a10-be554ebd6a41)

Somebody of my collaborators installed your plugin, and now all the records have the marking/tag "No INSPIRE recid found" above. How to make these tags not appearing in the list, and how can I get rid of this tag at all?

Thank you

**Comment by fkguo** [comment]
1) there is an option of not adding the tag: 
<img width="571" alt="image" src="https://github.com/user-attachments/assets/0e4024bf-d32e-42a4-9354-277f403f672a" />


2) The tag can be removed by using the plugin of ["Actions & Tags"](https://github.com/windingwind/zotero-actions-tags). you can set the following action, select the items, and then right click, then "Remove no INSPIRE tag"
<img width="367" alt="image" src="https://github.com/user-attachments/assets/be615aec-648e-44f7-ac66-48b156bcf544" />
