### ISSUE TITLE
is it possible to use inspire link as url instead of arxiv link?

### ISSUE THREAD

**Issue by quarkquartet** [fkguo/zotero-inspire#8]
As shown in title.

Before i find this, I use inspire link in url and use arxiv link in archive.

I'm imagining to use inspire link in url with some plugin automatically. For now I do not know where is the best place to put the arxiv link together.

Any thoughts? Is it possible?

**Comment by fkguo** [comment]
> As shown in title.
> 
> Before i find this, I use inspire link in url and use arxiv link in archive.
> 
> I'm imagining to use inspire link in url with some plugin automatically. For now I do not know where is the best place to put the arxiv link together.
> 
> Any thoughts? Is it possible?

yes it is possible. you can also find two tips in the readme, in the paragraph starting with "INSPIRE uses a unique `recid`", which can give you immediately the INSPIRE url.

Let me know whether you are satisfied by these tips.

I may also set an option to let the user to choose whether to use inspire or arxiv url when I have time.

**Comment by quarkquartet** [comment]
I just did it today but it does not work. My engine.json now looks like
```json
[
	{
		"_name": "Google Scholar",
		"_alias": "Google Scholar",
		"_description": "Google Scholar Search",
		"_icon": "file:///Users/quarkquartet/Zotero/locate/Google%20Scholar%20Search.ico",
		"_hidden": false,
		"_urlTemplate": "https://scholar.google.com/scholar?as_q=&as_epq={z:title}&as_occt=title&as_sauthors={rft:aufirst?}+{rft:aulast?}&as_ylo={z:year?}&as_yhi={z:year?}&as_sdt=1.&as_sdtp=on&as_sdtf=&as_sdts=22&",
		"_urlParams": [],
		"_urlNamespaces": {
			"rft": "info:ofi/fmt:kev:mtx:journal",
			"z": "http://www.zotero.org/namespaces/openSearch#",
			"": "http://a9.com/-/spec/opensearch/1.1/"
		},
		"_iconSourceURI": "https://scholar.google.com/favicon.ico"
	},
	{
		"_name": "INSPIRE",
		"_alias": "INSPIRE",
		"_description": "INSPIRE",
		"_icon": "https://inspirehep.net/favicon.ico",  // or local path to the INSPIRE icon,
		"_hidden": false,
		"_urlTemplate": "https://inspirehep.net/literature/{z:archiveLocation}",
		"_urlNamespaces": {
			"z": "http://www.zotero.org/namespaces/openSearch#"
		}
	},
	{
		"_name": "INSPIRE Citations",
		"_alias": "INSPIRE Citations",
		"_description": "INSPIRE citing papers",
		"_icon": "https://inspirehep.net/favicon.ico", 
		"_hidden": false,
		"_urlTemplate": "https://inspirehep.net/literature?q=refersto%3Arecid%3A{z:archiveLocation}",
		"_urlNamespaces": {
			"z": "http://www.zotero.org/namespaces/openSearch#"
		}
	},
]
```

Then I tried to update one of my entry manually after restarting zotero, now it still looks like:
<img width="687" alt="image" src="https://github.com/fkguo/zotero-inspire/assets/26316540/73fd0461-f212-4f70-81db-38479a8700e8">

Any thoughts?

Thank you for your reply.

**Comment by fkguo** [comment]
Hi, by "does not work", do you mean that the url shown in the `URL` slot is still the arxiv url instead of the INSPIRE one? editing the engine.json file does not change the url, but gives you a link to the INSPIRE page. Click the following button (I'm using Zotero 7; but Zotero 6 has the same functionality):
![image](https://github.com/fkguo/zotero-inspire/assets/62633089/b1c22700-0534-4ea0-97bf-2388d37b78ef)
you will get the following 
![image](https://github.com/fkguo/zotero-inspire/assets/62633089/b71fa0c8-2b98-4859-8bab-5b4a265f27b4)
which can lead you to the inspire page of the article and the page listing all papers citing that article.

using `Actions & Tags` plugin following the other tip I referred to allows you to copy the inspire url with keyboard shortcut.

**Comment by quarkquartet** [comment]
That sounds even better than I imagine. But I feel strange. I'm new to zotero 7 (used to be 6). I tried to click the button at the bottom in your first figure and nothing happens.

**Comment by fkguo** [comment]
> That sounds even better than I imagine. But I feel strange. I'm new to zotero 7 (used to be 6). I tried to click the button at the bottom in your first figure and nothing happens.

that is strange, it sounds like there is some problem with your lookup engines. You may try to ask what could have caused that in the Zotero forum.
