### ISSUE TITLE
获取不到相关信息，于是在所有条目下添加了一个“减号”标签，如何删除呢？

### ISSUE THREAD

**Issue by wisRen** [fkguo/zotero-inspire#9]
几乎给所有条目前面添加了个“红圈减号”。该怎么删除呢？左下角标签栏不显示，右小角显示，但只能一个个的删。
![80020FA2126A0771BF28E84B47A9454B](https://github.com/user-attachments/assets/0ea0a60e-97ba-47f0-8d4c-c4320c46d817)
![45E16B6F585A904F73F98A43AC77139B](https://github.com/user-attachments/assets/e2b94335-b944-4ca9-b1c7-732bc4a97da3)

**Comment by fkguo** [comment]
在偏好设置中，可以关掉这个标签功能，在设置中找到 Tag customization. If you don't want a tag, simply leave it empty，将"⛔ No INSPIRE recid found" 直接删除即可。在文件在 INSPIRE 数据库中有了这篇文献之后，更新过程中插件会将这个标签删除。

如果已经添加了的，可以通过 Actions & Tags 插件删除，在这个插件的设置中添加如下动作：
![image](https://github.com/user-attachments/assets/8f982b0a-893d-43b3-9b25-55c711441edf)
其中 ⛔ No INSPIRE recid 这一行没显示完全，要填为“⛔ No INSPIRE recid found”
这样，选中所有你想删除这个标签的条目，右键菜单中找到Remove no INSPIRE tag，点击就可以删除了

**Comment by wisRen** [comment]
谢谢。解决了。
